name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    uses: pmndrs/docs/.github/workflows/build.yml@v2
    with:
      mdx: 'docs'
      libname: 'prai'
      base_path: '/prai'
      icon: '🤖'
      home_redirect: '/getting-started/introduction'
      github: 'https://github.com/pmndrs/prai'
      discord: 'https://discord.gg/poimandres'

  deploy:
    needs: docs
    runs-on: ubuntu-latest
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

      # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
